### ISSUE TITLE
onPaste doesn't provide selected cell's row and column index

### ISSUE THREAD

**Issue by zachguo** [nadbm/react-datasheet#18]
Or is there an easy way to get copy-n-paste working?

**Comment by nadbm** [comment]
@zachguo 
One way to fix this would be to add the indexes right here: 
https://github.com/nadbm/react-datasheet/blob/master/src/DataSheet.js#L109

The alternative is to store the index on the cell's data itself since onPaste returns {cellData, pastedData} on for each cell. I guess it can be cumbersome as each cell needs to be initialized with the proper indexes

**Comment by nadbm** [comment]
Feel free to make a PR if you do end up adding the indexes

**Comment by zachguo** [comment]
Actually my problem is that, when editing cell content (after doubleclick), one cannot paste anything into the cell. 
![n53dkfbdcj](https://cloud.githubusercontent.com/assets/3478203/26423743/ab9dc80a-4083-11e7-8020-7688e51d21f0.gif)
(I tried pasting `react-datasheet` into A1 but failed, so basically expected behavior of input box is violated)

**Comment by nadbm** [comment]
I see, that's a different issue, and definitely a bug to be fixed. Basically should not be calling internal onPaste function if the cell is in editing mode

**Comment by zachguo** [comment]
Could you point to me where to change to get this fixed? I tried searching `input` and `editing`, but it's still not clear to me where to change.

**Comment by nadbm** [comment]
@zachguo I just pushed a commit, I'll get around to adding tests for it and pushing it to npm. But that should do it

**Comment by zachguo** [comment]
@nadbm Amazing, thanks!
