### ISSUE TITLE
row selection 

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#44]
is there any option to select row with checkbox on mouse hover 
like this
http://adazzle.github.io/react-data-grid/examples.html#/row-reordering
![screen shot 2017-11-30 at 5 41 03 pm](https://user-images.githubusercontent.com/9652523/33430246-e0812eec-d5f5-11e7-9fa2-089f6ca3a381.png)

**Comment by nadbm** [comment]
This is possible. 
This is slightly manual however:  you can use the 'component' attribute to have a checkbox in the first cell. See https://github.com/nadbm/react-datasheet#cells-with-underlying-component

When the checkbox is selected (keep this in your state), you can update your data so that cells in the row to have an extra className. That class can be whether or not cells are highlighted. 

Hope this helps.

**Comment by kamaldlk** [comment]
thanks

**Comment by konrad-garus** [comment]
This answer does not really feel correct. Selection is a grid feature, used for copy/paste and numerous other things. Setting a class on *my* components is just a bandaid to make it kind of look the same, which just adds confusion since it doesn't change behavior.

**Comment by nadbm** [comment]
hey @konrad-garus, note that this question referred to "hovering" over. Not actually changing the selection. 
I would suggest a controlled selection instead if you're planning on changing the selection https://github.com/nadbm/react-datasheet#advanced-options
