### ISSUE TITLE
Help Needed in context menu

### ISSUE THREAD

**Issue by kamaldlk** [nadbm/react-datasheet#87]
@weswigham I'm trying to add context menu below image I'm not able to get Menu can anyone help me on this
![screen shot 2018-04-23 at 11 18 32 pm](https://user-images.githubusercontent.com/9652523/39143865-b468e7c8-474c-11e8-8e57-f3609fb601d0.png)

**Comment by weswigham** [comment]
So, I last used it a long time ago, but I was just using https://github.com/weswigham/crossword-filler/blob/master/src/components/Grid.tsx#L32 which was set by https://github.com/weswigham/crossword-filler/blob/master/src/App.tsx#L134 - I was using it to capture right-click and disable the default context menu. The stable API may have changed a bit since then.

**Comment by nadbm** [comment]
@kamaldlk you can use the "event" from onContextMenu prop to determine where in the page the right click was called. From that you can place your custom context menu.
Something like this: http://jsfiddle.net/ga7mm3cc/

**Comment by kamaldlk** [comment]
@weswigham , @nadbm yes I did Working Thanks : )
![screen shot 2018-04-24 at 3 41 05 pm](https://user-images.githubusercontent.com/9652523/39180983-ebecbe52-47d5-11e8-839f-51225c3d7a9c.png)
