### ISSUE TITLE
Using a key to leave a cell triggers onChange twice

### ISSUE THREAD

**Issue by BluFoot** [nadbm/react-datasheet#97]
Pressing enter for example first triggers `DataCell::handleKey`, calling `handleCommit`, calling `onChange`. 

Then on the next render, `componentDidUpdate` is called, which again calls `onChange`.

**Comment by nadbm** [comment]
The ```onChange``` api causes that as it's called on every state change. Use the following API instead: 
https://github.com/nadbm/react-datasheet#oncellschangedarrayofchanges-arrayofadditions-handler

**Comment by jrball3** [comment]
@nadbm The onCellsChanged falls victim to this problem as well, but maybe under different circumstances.  It's my understanding that if we chain some actions that alter the data that feeds the cells value off of `handleCommit`'s first call to `onChange`, then by the time the second check comes around in `componentDidUpdate` the state has changed and triggers the `onChange` handler again.  As a result we are seeing two calls to our `onCellsChanged` handler for any edit, since we are resetting the value of the cell when we see an edit.

**Comment by nadbm** [comment]
Right, I just noticed this as well. I’ll try to find a proper fix for this asap

**Comment by nadbm** [comment]
fixed on @7027ad0db5d54a36f49ebef77dcdae4ea8ade976
